// Generated by https://quicktype.io

export interface AuthResponse {
    ok:    boolean;
    data:  User;
    token: string;
}

export interface Login{
    email: string;
    password: string;
}

export interface Register extends Login{
    name: string;
}

export interface User {
    uid:               string;
    name:              string;
    email?:             string;
    bio?:               string;
    imgUser:           string;
    imgUserBackground?: string;
    loginGoogle?:       boolean;
    posts?:             string[];
    retweets?:          string[];
    saved?:             string[];
    likes?:             string[];
    followers?:         string[];
    following?:         string[];
    nfollowers?:        number;
    nfollowing?:        number;
}
