// Generated by https://quicktype.io

export interface FollowResponse {
    ok:   boolean;
    uid:  string;
    data: IUserFollow[];
}

export interface IUserFollow {
    name:      string;
    bio:       string;
    imgUser:   string;
    followers: string[];
    uid:       string;
}
