// Generated by https://quicktype.io

export interface FollowResponse {
    ok:   boolean;
    uid:  string;
    data: IUserFollow[];
}

export interface IUsersResponse {
    ok:   boolean;
    length: number,
    data: IUserFollow[];
}


export interface IUserFollow {
    name:      string;
    bio:       string;
    imgUser:   string;
    imgUserBackground?: string;
    followers: string[];
    uid:       string;
}
