// Generated by https://quicktype.io

export interface PostsResponse {
    ok:     boolean;
    length: number;
    data:   IPost[];
}

export interface IPost {
    tid:           string;
    date:          string;
    userTweet:     IUserProfile;
    description:   string;
    hashtagsTweet: string[];
    imgTweet?:     string;
    showEveryone:  boolean;
    showFollow:    boolean;
    nRetweets:     number;
    nSaved:        number;
    saved:         string[];
    nLikes:        number;
    likes:         string[];
    nComentPeople: number;
    retweets:      string[];
    comentPeople:  ComentPerson[];
    userRetweet?:  string;
}

export interface ComentPerson {
    cid:          string;
    userComment:  IUserProfile;
    tweetComment: string;
    commentText:  string;
    nLikes:       number;
    likes:        string[];
    date:         string;
}

export interface IUserProfile {
    name:    string;
    imgUser: string;
    uid:     string;
}

export interface IDetailPost {
    likes: string[];
    nLikes: number;
    comments: ComentPerson[];
    nComments: number;
    retweet: string[];
    nRetweets: number;
    saved: string[];
    nSaved: number;
}

export interface ActionResponse{
    msg: string;
    ok: boolean;
}